# Generated by Django 2.0.4 on 2018-04-29 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(choices=[(-5, 'Muito frio'), (10, 'Frio'), (20, 'Quente'), (35, 'Muito quente')], default=20)),
                ('rainy', models.IntegerField(choices=[(0, 'Nenhuma chance'), (100, 'Chuva com certeza')], default=0)),
                ('length', models.IntegerField(choices=[(3, '3 dias'), (7, '7 dias'), (11, '11 dias'), (14, '+14 dias')], default=7)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
