# Generated by Django 2.0.4 on 2018-05-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180430_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='temperature_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='temperature_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='temperature_variation',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travel',
            name='temperature',
            field=models.IntegerField(choices=[(0, 'Muito frio'), (10, 'Frio'), (20, 'Quente'), (30, 'Muito quente')], default=20),
        ),
    ]
