# Generated by Django 2.0.4 on 2018-05-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180503_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='temperature_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='temperature_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='temperature_variation',
        ),
        migrations.AddField(
            model_name='product',
            name='base_qtd_cold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='base_qtd_cool',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='base_qtd_hot',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='base_qtd_warm',
            field=models.FloatField(default=0),
        ),
    ]
