# Generated by Django 2.0.4 on 2018-05-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180503_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_qtd_cold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_qtd_cool',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_qtd_hot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='base_qtd_warm',
        ),
        migrations.AddField(
            model_name='product',
            name='qtd_cold_base',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qtd_cool_base',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qtd_hot_base',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='qtd_warm_base',
            field=models.FloatField(default=0),
        ),
    ]
