# Generated by Django 2.0.4 on 2018-05-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180503_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multiply_by_days',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('m', 'Homem'), ('f', 'Mulher'), ('u', 'Unisex')], default='u', max_length=1),
        ),
    ]
