# Generated by Django 2.0.4 on 2018-05-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180503_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(choices=[(0, 'Muito frio'), (10, 'Frio'), (20, 'Quente'), (30, 'Muito quente')], default=20)),
                ('length', models.IntegerField(choices=[(3, '3 dias'), (7, '7 dias'), (11, '11 dias'), (14, '+14 dias')], default=7)),
                ('sex', models.CharField(choices=[('m', 'Homem'), ('f', 'Mulher')], default='f', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='core.Product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='travel',
            name='products',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
