# Generated by Django 2.0.4 on 2018-05-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(choices=[(0, 'Muito frio'), (10, 'Frio'), (20, 'Quente'), (30, 'Muito quente')], default=20)),
                ('days', models.IntegerField(choices=[(3, '3 dias'), (7, '7 dias'), (11, '11 dias'), (14, '+14 dias')], default=7)),
                ('sex', models.CharField(choices=[('m', 'Homem'), ('f', 'Mulher')], default='f', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackpackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(default=0)),
                ('backpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Backpack')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('for_male', models.BooleanField(default=True)),
                ('for_female', models.BooleanField(default=True)),
                ('multiply_by_days', models.BooleanField(default=True)),
                ('qtd_cold_base', models.FloatField(default=0)),
                ('qtd_cool_base', models.FloatField(default=0)),
                ('qtd_warm_base', models.FloatField(default=0)),
                ('qtd_hot_base', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.AddField(
            model_name='backpackitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
