# Generated by Django 2.0.4 on 2018-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/placeholder.png', upload_to='product/'),
        ),
    ]
