# Generated by Django 2.0.4 on 2018-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product-placeholder.png', upload_to='product/'),
        ),
    ]
