# Generated by Django 2.0.4 on 2018-05-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180507_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qtd_cold_base',
            new_name='qtd_cold',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qtd_cool_base',
            new_name='qtd_cool',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qtd_hot_base',
            new_name='qtd_hot',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qtd_warm_base',
            new_name='qtd_warm',
        ),
    ]
