# Generated by Django 2.0.4 on 2018-05-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180510_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBackpack',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Product')),
                ('trip_duration', models.IntegerField(default=0)),
            ],
            bases=('app.product',),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
