# Generated by Django 2.0.4 on 2018-05-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180510_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='backpack_for_duration',
            new_name='trip_duration',
        ),
    ]
