# Generated by Django 2.0.4 on 2018-05-10 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180510_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpack',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
