# Generated by Django 2.0.4 on 2018-05-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
    ]
