# Generated by Django 2.0.4 on 2018-05-18 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180517_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpack',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
