# Generated by Django 2.1.3 on 2018-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181201_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpack',
            name='temp',
            field=models.IntegerField(default=20),
        ),
    ]
