# Generated by Django 2.1.3 on 2018-12-01 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20181201_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='backpack',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='backpack',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='backpack',
            name='days',
            field=models.IntegerField(default=7),
        ),
    ]
