# Generated by Django 2.1.3 on 2018-12-02 21:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20181201_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpack',
            name='end_date',
            field=models.DateField(default=app.models.Backpack.default_end_date),
        ),
    ]
