# Generated by Django 2.1.3 on 2018-12-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20181202_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backpack',
            name='place',
            field=models.CharField(default='Paris, França', max_length=1024),
        ),
    ]
